name: Digitial Sanitation Engineering
markdown: redcarpet
redcarpet:
    extensions: ["hard_wrap", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]

pygments: true
